#!/usr/bin/env python3
"""Build the generated part of factory/interfaces.md from the 64 Interfaces tables.

Usage:  python3 tools/build_interfaces.py           rewrite the block between the markers
        python3 tools/build_interfaces.py --check   exit 1 if the block is not up to date

The page keeps its hand-written parts; only the block between these two markers is generated:
    <!-- generated by tools/build_interfaces.py: start -->
    <!-- generated by tools/build_interfaces.py: end -->
tools/check_factory.py runs the same comparison, so a page that has drifted from the tables is an
error there too. Standard library only.
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_factory as cf  # noqa: E402

PAGE = cf.FACTORY / "interfaces.md"
START = "<!-- generated by tools/build_interfaces.py: start -->"
END = "<!-- generated by tools/build_interfaces.py: end -->"
SECTIONS = [f"S{n}" for n in range(1, 8)]
# The streams every page may send to one gathering page; counted apart from the design flows.
STANDARD = ["kpi-feed", "decision-log", "runbook", "mission-card"]


def id_key(value: str) -> tuple:
    if value.startswith("S"):
        section, number = value[1:].split(".")
        return (int(section), int(number))
    return (99, 0 if value == "lab" else 1)


def compress(ids) -> str:
    """S1.1, S1.2, S1.3, S2.4 -> 'S1.1–S1.3, S2.4'; the whole of a section -> 'all of S1';
    nearly every sub-section -> 'all but S6.1'."""
    ids = sorted(set(ids), key=id_key)
    missing = [value for value in cf.ALL_IDS if value not in ids]
    if not missing:
        return "all 64 sub-sections"
    if len(missing) <= 3 and all(value in cf.VALID_IDS for value in ids):
        return "all but " + ", ".join(missing)
    out, run = [], []
    for value in ids + [None]:
        if run and value and value.startswith("S") and run[-1].startswith("S"):
            (s1, n1), (s2, n2) = id_key(run[-1]), id_key(value)
            if s1 == s2 and n2 == n1 + 1:
                run.append(value)
                continue
        if run:
            section = id_key(run[0])[0]
            if run[0].startswith("S") and len(run) == cf.SUBSECTION_COUNTS[section - 1]:
                out.append(f"all of S{section}")
            elif len(run) >= 3:
                out.append(f"{run[0]}–{run[-1]}")
            else:
                out.extend(run)
        run = [value] if value else []
    return ", ".join(out)


def collect() -> dict:
    """{sub-section ID: its Interfaces rows}, read as check_factory.py reads them."""
    report = cf.Report()
    return {sub_id: cf.check_interfaces(page, cf.read_lines(page), report)
            for sub_id, page in cf.read_index(report).items() if page.exists()}


def build(flows: dict) -> str:
    producers, readers, label = defaultdict(set), defaultdict(set), {}
    matrix = Counter()
    pairs = defaultdict(set)
    for sub_id, rows in flows.items():
        for _, direction, key, name, values in rows:
            label[key] = name
            if direction == "out":
                producers[key].add(sub_id)
                readers[key] |= values
                if key in STANDARD:
                    continue
                for value in values:
                    matrix[(sub_id.split(".")[0], value.split(".")[0] if value.startswith("S") else value)] += 1
                    if value in flows:
                        pairs[(sub_id, value)].add(key)
            else:
                readers[key].add(sub_id)
                producers[key] |= values
    link = lambda key: f"[{label[key]}](glossary.md#{key})"  # noqa: E731
    lines = [START, "", "## Between sections", "",
             "How many design flows each section sends to each section (the diagonal counts the flows "
             "inside a section) and to the research lab. A row that names several readers counts once per "
             "reader; the standard streams are counted apart, in the next table.", "",
             "| From \\ To | " + " | ".join(SECTIONS) + " | lab |", "|---|" + "---|" * 8]
    for section in SECTIONS:
        cells = [str(matrix[(section, other)] or "·") for other in SECTIONS + ["lab"]]
        lines.append(f"| **{section}** | " + " | ".join(cells) + " |")
    external = sorted((key for key in producers if "external" in producers[key]), key=lambda k: label[k].lower())
    lines += ["", "From outside the factory: " + ", ".join(link(k) for k in external) + ".", "",
              "## The standard streams", "",
              "What every page may send to the one page that gathers it, and the few pages that also read "
              "some of them (with the number of senders each reads).", "",
              "| Stream | Pages | Sent by | Gathered by |", "|---|---|---|---|"]
    for key in STANDARD:
        senders = producers[key] - {"external", "lab"}
        per_reader = Counter(value for rows in flows.values() for _, direction, k, _, values in rows
                             if direction == "out" and k == key for value in values)
        main, *others = sorted(per_reader, key=lambda r: (-per_reader[r], id_key(r)))
        gathered = main + ("; also " + ", ".join(f"{r} ({per_reader[r]})" for r in others) if others else "")
        lines.append(f"| {link(key)} | {len(senders)} | {compress(senders)} | {gathered} |")
    lines += ["", "## Every artefact", "",
              f"The {len(label)} artefacts, in alphabetical order: who produces each one, who reads it.", "",
              "| Artifact | Produced by | Read by |", "|---|---|---|"]
    for key in sorted(label, key=lambda k: label[k].lower()):
        lines.append(f"| {link(key)} | {compress(producers[key])} | {compress(readers[key])} |")
    loops = sorted({tuple(sorted(pair, key=id_key)) for pair in pairs if (pair[1], pair[0]) in pairs},
                   key=lambda p: (id_key(p[0]), id_key(p[1])))
    lines += ["", "## Pages that feed each other", "",
              "Pairs of sub-sections with a design flow each way, and what travels in each direction.", "",
              "| Pages | One way | The other way |", "|---|---|---|"]
    for a, b in loops:
        there = ", ".join(sorted(label[k] for k in pairs[(a, b)]))
        back = ", ".join(sorted(label[k] for k in pairs[(b, a)]))
        lines.append(f"| {a} ↔ {b} | {a} → {b}: {there} | {b} → {a}: {back} |")
    lines += ["", END]
    return "\n".join(lines)


def rebuilt(text: str, flows: dict) -> str | None:
    """The page's text with its generated block rebuilt, or None if a marker is missing."""
    if START not in text or END not in text:
        return None
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return head + build(flows) + tail


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if factory/interfaces.md is not up to date")
    args = parser.parse_args()
    text = PAGE.read_text(encoding="utf-8")
    new = rebuilt(text, collect())
    if new is None:
        print(f"{PAGE}: markers missing", file=sys.stderr)
        return 1
    if args.check:
        if new != text:
            print("factory/interfaces.md is not up to date: run python3 tools/build_interfaces.py", file=sys.stderr)
            return 1
        print("factory/interfaces.md is up to date")
        return 0
    PAGE.write_text(new, encoding="utf-8")
    print("factory/interfaces.md rebuilt")
    return 0


if __name__ == "__main__":
    sys.exit(main())
